plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    // Cliente de Appium para Java (incluye Selenium)
    testImplementation 'io.appium:java-client:9.3.0'
    testImplementation 'junit:junit:4.13.2'
}

test {
    useJUnit()
}